<a href="https://colab.research.google.com/github/Kommireddikrishnasuji/22MH1A42A3/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as nd
import  pandas as pd
from sklearn import datasets
d1=datasets.load_iris()
d1

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
d2=pd.DataFrame(d1.data)
d2

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
d2.head

<bound method NDFrame.head of        0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]>

In [ ]:
d2[0:4]

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [ ]:
d2[0:2]

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2

In [ ]:
d2[:1]

0    1    2    3
0  5.1  3.5  1.4  0.2

In [ ]:
d2[::2]

0    1    2    3
0    5.1  3.5  1.4  0.2
2    4.7  3.2  1.3  0.2
4    5.0  3.6  1.4  0.2
6    4.6  3.4  1.4  0.3
8    4.4  2.9  1.4  0.2
..   ...  ...  ...  ...
140  6.7  3.1  5.6  2.4
142  5.8  2.7  5.1  1.9
144  6.7  3.3  5.7  2.5
146  6.3  2.5  5.0  1.9
148  6.2  3.4  5.4  2.3

[75 rows x 4 columns]

In [ ]:
d2[:-1]

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
144  6.7  3.3  5.7  2.5
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3

[149 rows x 4 columns]

In [ ]:
d2[::5]

0    1    2    3
0    5.1  3.5  1.4  0.2
5    5.4  3.9  1.7  0.4
10   5.4  3.7  1.5  0.2
15   5.7  4.4  1.5  0.4
20   5.4  3.4  1.7  0.2
25   5.0  3.0  1.6  0.2
30   4.8  3.1  1.6  0.2
35   5.0  3.2  1.2  0.2
40   5.0  3.5  1.3  0.3
45   4.8  3.0  1.4  0.3
50   7.0  3.2  4.7  1.4
55   5.7  2.8  4.5  1.3
60   5.0  2.0  3.5  1.0
65   6.7  3.1  4.4  1.4
70   5.9  3.2  4.8  1.8
75   6.6  3.0  4.4  1.4
80   5.5  2.4  3.8  1.1
85   6.0  3.4  4.5  1.6
90   5.5  2.6  4.4  1.2
95   5.7  3.0  4.2  1.2
100  6.3  3.3  6.0  2.5
105  7.6  3.0  6.6  2.1
110  6.5  3.2  5.1  2.0
115  6.4  3.2  5.3  2.3
120  6.9  3.2  5.7  2.3
125  7.2  3.2  6.0  1.8
130  7.4  2.8  6.1  1.9
135  7.7  3.0  6.1  2.3
140  6.7  3.1  5.6  2.4
145  6.7  3.0  5.2  2.3

In [ ]:
d2.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE=(LabelEncoder)
from sklearn.preprocessing import OrdinalEncoder
OE=OrdinalEncoder()
from sklearn.preprocessing import OneHotEncoder
OHE=OneHotEncoder()
d3=OE.fit_transform(d2[0:4])
d3

array([[3., 3., 1., 0.],
       [2., 0., 1., 0.],
       [1., 2., 0., 0.],
       [0., 1., 2., 0.]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
MMS=MinMaxScaler()
SS=StandardScaler()
x=d2.iloc[:,1:4]
x
y=d2.iloc[:,0:1]
y
MMS.fit_transform(d3)

array([[1.        , 1.        , 0.5       , 0.        ],
       [0.66666667, 0.        , 0.5       , 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.        ],
       [0.        , 0.33333333, 1.        , 0.        ]])

In [ ]:
x

1    2    3
0    3.5  1.4  0.2
1    3.0  1.4  0.2
2    3.2  1.3  0.2
3    3.1  1.5  0.2
4    3.6  1.4  0.2
..   ...  ...  ...
145  3.0  5.2  2.3
146  2.5  5.0  1.9
147  3.0  5.2  2.0
148  3.4  5.4  2.3
149  3.0  5.1  1.8

[150 rows x 3 columns]

In [ ]:
y

0
0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
..   ...
145  6.7
146  6.3
147  6.5
148  6.2
149  5.9

[150 rows x 1 columns]

In [ ]:
d3

array([[3., 3., 1., 0.],
       [2., 0., 1., 0.],
       [1., 2., 0., 0.],
       [0., 1., 2., 0.]])

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.8,random_state=123)

In [ ]:
X_train

1    2    3
130  2.8  6.1  1.9
119  2.2  5.0  1.5
29   3.2  1.6  0.2
0    3.5  1.4  0.2
62   2.2  4.0  1.0
..   ...  ...  ...
17   3.5  1.4  0.3
98   2.5  3.0  1.1
66   3.0  4.5  1.5
126  2.8  4.8  1.8
109  3.6  6.1  2.5

[120 rows x 3 columns]